
NORMALNUMPY = 1
NUMPY_SHAPE_N_2 = 0
MAXPIXELSEPARATION = 10 # need to adjust experimentally
MARGIN = 30
FRAGMENT = 0
CONTOUR = 1
ENHANCEMODE = 0
DONOTENHANCE = 1

'''
user defined params
'''
NPOINTS = 3
THRESHOLD = 254
ACCURACY = 3
ANGLEDIFF = 1
C_THRESHOLD = 0.1
FLAT_THRESHOLD = ANGLEDIFF+1
MIN_AREA = 50
# 2 or 3 optimum
MATCH=2
MISMATCH=-1
SPACE=-1

def getMatchScore(iter):
    return MATCH+iter